alias g='git'
alias gs='git status'
alias gc='git add . && git commit -m'
alias ga='git add . && git commit --amend --no-edit'
alias gl='git log --oneline'
alias gpush='git push'
alias gpull='git pull'
alias gr='git reset'